### ISSUE TITLE
SDK does not handle pagination properly

### ISSUE THREAD

**Issue by SNikon** [Accedo-Products/accedo-one-sdk-express#1]
Hi,

When requesting more entries than the maximum the appgrid system will provide, the SDK will not handle pagination properly, and will delete the necessary data for the client to handle.

If the client requests a list of entries of numbers above 20, appgrid will provide the total value and the size of the actual returned data. Unfortunately, this pagination is ignored by appgrid-express and only the first 20 are returned and the pagination info is removed. vdkweb-vikimap unfortunately does not take this into consideration and requests the full number of items and,as far as I can tell, expects this number of items. To make sure that existing VDKWEB apps are not affected negatively appgrid-express should fetch all the pages and keep the resulting data in the same model as it currently is.

How to reproduce:
Request at least 21 different published IDs from /entries request.
Expected Result:
The number of elements returned is 21.
Actual Result:
The number of elements returned will be 20.

Best Regards!

**Comment by gouegd** [comment]
Hi @SNikon  !

Here's a sample response to a call to `res.locals.appgridClient.getEntries()` :
```
{"entries":[{"_meta":{"id":"56ea7bd6935f75032a2fd431","typeId":"56ea7bca935f75032a2fd42c","typeTags":["Example"],"typeAlias":"exampleentrytype","entryAlias":"erik","attrs":{"exampleAttribute":"exampleValue"},"publishedFrom":"2017-04-13T09:44:00Z"},"somefield":"Example Entry","hello":"bonjour"},{"_meta":{"id":"56ea7c55935f75032a2fd437","typeId":"56ea7bca935f75032a2fd42c","typeTags":["Example"],"typeAlias":"exampleentrytype","entryAlias":"greg","attrs":{"exampleAttribute":"exampleValue"},"publishedFrom":"2016-03-17T09:43:00Z"},"somefield":"Another example field"}],"pagination":{"total":2,"size":20,"offset":0}}
```

As you can see, the pagination info is not removed.

In a general fashion, the SDK does not remove anything from the AppGrid API responses it relays requests to.
Pagination has to be handled manually as this is not part of the features the SDK provides. If there is demand for it, I can imagine it being added though.

**Comment by gouegd** [comment]
@mikeleung @szeng could it be that `vdkweb-vikimap` removes the pagination info ?

**Comment by SNikon** [comment]
Hi @gouegd ,

The data that you show me is not what I receive from this middleware.
Please find inline a bit of a massive example

`https://revamp.shahid.net/vikimap/entries/591ddbd623eec60006cec3fb,5953693323eec60006c927a3,58c8f9b8115e8d0215ef6bbb,58c8fa0b115e8d0215ef6c13,59a3f4491de1c4000dfae23c,5921b5bca0e845000621276c,5922998ba0e8450006212aad,59959bd023eec6000c4de6ea,59958b8423eec6000c4de68f,599d7bb51de1c4000df98279,5947b2b3a0e8450006cb44ac,593fa5a623eec60006e0b7de,593fa77e23eec60006e0b842,594787d6a0e8450006cb3ea7,59478c95a0e8450006cb3ed7,59478eeea0e8450006cb3f08,596b70e0a0e845000d212d8f,587ab81d08bf8201f9c4be47,58c8f4a51d8243020fdd7be3,58c7a711219ae4022581e3ba,58c02eaeabe89d021f9609a9,58c02cd5abe89d021f96097b,58c03074abe89d021f9609d1,58c03223abe89d021f960a11,58c03107abe89d021f9609ef,58c032b8abe89d021f960a4b,58c8d6041d8243020fdd7864,58c8d9c61d8243020fdd789d,58c8d8631d8243020fdd788a,58c7c960219ae4022581e614,58c42428d89cf202313a742f,58c423bfd89cf202313a741a,58c423a3d89cf202313a7402,58c420a4d89cf202313a73c4,58c421dcd89cf202313a73eb,58c41c79d89cf202313a7378`

You'll find that unless this SDK uses vdkweb-vikimap internally, this should not be related. I do believe that even if this information did exist vdkweb-vikimap would NOT be handling it, and this is critical as the app never receives this information to attempt to handle it itself.

**Comment by gouegd** [comment]
This shows me the result, but I'd need to see the server code to see how the SDK is being used.
Can you share this code or the appId so I can replicate ?

**Comment by SNikon** [comment]
Hi.

I checked with your information and you seem to be correct, I mistakenly assumed that this was related to appgrid-middleware but it seems to be related to the vikimap one, unfortunately I was not aware this existed by default.

From what I can see here

`entryMiddleware.get('/entries/:ids', withEntryProvider(function (req, res, entryProvider) {
    var ids = req.params.ids ? req.params.ids.split(',') : [];

    entryProvider.getEntriesByIds(ids).then(function (entries) {
      return res.send(entries);
    }).catch(errorHandler(req, res, 500, 'Failed to get the vikimap entries: ' + req.params.ids));
  }));`

vikimap does not handle this fully. "GetEntriesByIds" does indeed remove the data you were talking about without covering it themselves for pagination.

@mikeleung @szeng  please advise over "vdkweb-vikimap": "^1.3.0"

**Comment by gouegd** [comment]
Closed as a vikimap issue
